<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" name="subhelpers_tests.MyTest-20190217212715" skipped="0" tests="1" time="0.003" timestamp="2019-02-17T21:27:15">
	<testcase classname="subhelpers_tests.MyTest" name="test_cityname" time="0.003" timestamp="2019-02-17T21:27:15">
		<error message="[Errno 2] No such file or directory: '/home/amitra/environments/data/UNLOCODE.txt'" type="FileNotFoundError">
<![CDATA[Traceback (most recent call last):
  File "/home/amitra/environments/Weather/src/unittest/python/subhelpers_tests.py", line 11, in test_cityname
    self.assertEqual(getcityname('LAS'), 'Las Vegus')
  File "/home/amitra/environments/Weather/src/main/python/subhelpers.py", line 17, in getcityname
    with open(getdatafile("UNLOCODE.txt"), encoding='cp1252') as countryfile:
FileNotFoundError: [Errno 2] No such file or directory: '/home/amitra/environments/data/UNLOCODE.txt'
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
