<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" name="unittest.loader._FailedTest-20190214075510" skipped="0" tests="1" time="0.001" timestamp="2019-02-14T07:55:10">
	<testcase classname="unittest.loader._FailedTest" name="core_tests" time="0.001" timestamp="2019-02-14T07:55:10">
		<error message="Failed to import test module: core_tests
Traceback (most recent call last):
  File &quot;/usr/lib/python3.6/unittest/loader.py&quot;, line 153, in loadTestsFromName
    module = __import__(module_name)
  File &quot;/home/amitra/environments/Weather/src/unittest/python/core_tests.py&quot;, line 5, in &lt;module&gt;
    from myproject import greet
ModuleNotFoundError: No module named 'myproject'
" type="ImportError">
<![CDATA[ImportError: Failed to import test module: core_tests
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/home/amitra/environments/Weather/src/unittest/python/core_tests.py", line 5, in <module>
    from myproject import greet
ModuleNotFoundError: No module named 'myproject'

]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
