<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" name="unittest.loader._FailedTest-20190217200616" skipped="0" tests="1" time="0.001" timestamp="2019-02-17T20:06:16">
	<testcase classname="unittest.loader._FailedTest" name="subhelpers_tests" time="0.001" timestamp="2019-02-17T20:06:16">
		<error message="Failed to import test module: subhelpers_tests
Traceback (most recent call last):
  File &quot;/usr/lib/python3.6/unittest/loader.py&quot;, line 153, in loadTestsFromName
    module = __import__(module_name)
  File &quot;/home/amitra/environments/Weather/src/unittest/python/subhelpers_tests.py&quot;, line 5, in &lt;module&gt;
    from src.main.python.subhelpers import getcityname
ModuleNotFoundError: No module named 'src'
" type="ImportError">
<![CDATA[ImportError: Failed to import test module: subhelpers_tests
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/home/amitra/environments/Weather/src/unittest/python/subhelpers_tests.py", line 5, in <module>
    from src.main.python.subhelpers import getcityname
ModuleNotFoundError: No module named 'src'

]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
